name: "first workflow"
    
on: 

    push:
            branches:
                    - main
                    - developer

jobs:
    hello-world:
      runs-on: ubuntu-latest
      steps:
              - name: "print hello world"
                run: echo "hello world"


