name: "multi-event pipelive/workflow"
on:
        push: # Event: whenever a push is made to the repository on the master / test branch
             branches:
                     - master
                     - test

        pull_request: # Event: whenever a pull request is made to the repository
             branches:
                     - master

jobs:     # here both jobs will run if even one event is triggerd 

        on-push:   # job 1
                runs-on: ubuntu-latest
                steps: # step 1
                       - name: "echo running on master/test push"
                         run: echo "running on master/test push"

        on-pull_request:  # job 2
                 runs-on: ubuntu-latest
                 steps: # step 1
                       - name: "echo pull-request"
                         run: echo "pull-request"
