name: "multi-event pipeline/workflow"

on:
  push:  # Event: whenever a push is made to the repository on the master / test / main branch
    branches:
      - master
      - test
      - main

  pull_request:  # Event: whenever a pull request is made to the repository
    branches:
      - master

  workflow_dispatch:  # Event: manual trigger from GitHub Actions UI

jobs:  # jobs will run conditionally based on the event type (push, pull_request, or workflow_dispatch)

  on-push:  # job 1
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:  # step 1
      - name: "echo running on master/test push"
        run: echo "running on master/test push"

  on-pull_request:  # job 2
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:  # step 1
      - name: "echo pull-request"
        run: echo "pull-request"

  on-dispatch:  # job 3
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:  # step 1
      - name: "echo dispatch"
        run: echo "workflow manually dispatched"

